version: 2
jobs:
  tox:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo pip install tox flake8
      - run:
          name: Run tox
          command: tox
    working_directory: ~/teleserver
workflows:
  version: 2
  tox_test:
    jobs:
      - tox
